FROM node:18-alpine as production

WORKDIR /workspace

COPY package.json  /workspace/

RUN yarn

COPY . .

ENV PORT 3000

RUN yarn build customer

RUN rm -rf apps libs

CMD ["node", "dist/apps/member-api/main.js"]