export const DTAC_SERVICE = 'DTAC_SERVICE';
export const OTP_SERVICE = 'OTP_SERVICE';
export const DLR_SERVICE = 'DLR_SERVICE';
export const CUSTOMER_SERVICE = 'CUSTOMER_SERVICE';
export const PUBLIC_SERVICE = 'PUBLIC_SERVICE';
export const WORKER_SERVICE = 'WORKER_SERVICE';
export const NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE';
